### ISSUE TITLE
Bug: User color and message color mismatch

### ISSUE THREAD

**Issue by saygo-png** [ulyssa/iamb#243]
When using `message_user_color = true` and changing the colors of a user with `"@saygo.2:tchncs.de" = { color = "none" }` the color of the message does not change, and still uses the default option creating a mismatch. It also happens with colors other than `none`

![image](https://github.com/ulyssa/iamb/assets/131687037/14207574-a560-484d-9328-d8e2de25ca87)
_my messages here should be in white (color "none")_
<details>
<summary>Debug info</summary>

### Config
```toml
[profiles."example.com"]
user_id = "@saygo.2:tchncs.de"
[layout]
style = "restore"
[settings]
default_room = "@ronniehoney:matrix.org"
message_user_color = true
username_display = "localpart"
user_gutter_width = 9
[settings.notifications]
enabled = true
[macros."normal"]
";" = ":"
[settings.users]
"@saygo.2:tchncs.de" = { color = "none" }
"@ronniehoney:matrix.org" = { color = "red" }
"@toasterbirb:tchncs.de" = { color = "yellow" }
```
### Output of `iamb --version`:
`iamb 0.0.9 (83b90c84)`
</details>
