### ISSUE TITLE
feature request: command to go to room/chat

### ISSUE THREAD

**Issue by yara-blue** [ulyssa/iamb#357]
I have tried adding a macro that goes to the chat however the macro only opens the chats screen. This might be the wrong way to do that too. Could we have a command to open a room/dm/space?

```toml
[macros.normal]
"gy" = ":chats<Enter>/Name (DM)<Enter>" 
```
