### ISSUE TITLE
provide JSON Schema to allow validating config file

### ISSUE THREAD

**Issue by KiaraGrouwstra** [ulyssa/iamb#400]
We now have a [sample config](https://github.com/ulyssa/iamb/blob/main/config.example.toml), which helps users get going to tweak their own setup.
To further facilitate this, it would be nice to offer a corresponding [JSON Schema](https://json-schema.org/) file. This would then enable validating checks for the config, including by LSP language servers for TOML such as [taplo](https://github.com/tamasfe/taplo).

It should be possible to generate this using say [schemars](https://github.com/GREsau/schemars).

**Comment by JIbald** [comment]
Can confirm, I get 
`No configured profile with the name "<username>" in .config/iamb/config.json`
and no clue what to do.

**Comment by KiaraGrouwstra** [comment]
<details>
<summary>

@JIbald as per your specific configuration issue, you may consider what i used there (click to expand), but yeah some systematic feedback mechanism would be nicer.

</summary>

```toml
default_profile = "foo"
# if not specified uses "default"

[profiles.foo]
user_id = "..."
url = "..."
...
```

</details>
