### ISSUE TITLE
[Feature Request] User-Specified Registers

### ISSUE THREAD

**Issue by fuguesoft** [ulyssa/iamb#410]
Is it possible to tell iamb to use the unnamed register when yanking/deleting? 
It would be cool if it were possible to specify this in the config.toml

something like:
```toml
[settings.clipboard]
default_register = "unnamedplus"
```

If one wanted, they might specify iamb to always use the `a` register or the `q` one for whatever reason.
